config/routes.rb
Intersection::Application.routes.draw do
  get "page/index"
  get "page/load_album_images"
  post "page/move"

  match '/accounts/new/:provider' => 'account#new', :as => "new_account"
  match '/accounts/:action' => 'account'
  match '/r' => "account#reset", :as => "logout"
  match '/cf' => "account#check_flickr_token"
  match '/page/refresh/:provider' => 'page#refresh', :as => "refresh"

  root :to => "page#index"

end

app/views/page/index.html.erb
<html>
<head>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js"></script>
  <%= stylesheet_link_tag "intersection.css" %>

  <%= javascript_include_tag "application" %>


  <title>Intersection: Social Media Dropbox</title>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3177874-6']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script');
      ga.type = 'text/javascript';
      ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>

<div id="stage">&nbsp;</div>

<%= link_to "logout", logout_path, :id => "logout" if session[:flickr_account_id] or session[:facebook_account_id] %>

<div id="prompt">
  <div class="explanation">
    <h1>Social Media Dropbox</h1>

    <h2>Move photos between Flickr and Facebook</h2>
    <% unless session[:flickr_account_id] and session[:facebook_account_id] %>
      <p>After connecting to both services, you'll be able to drag your photos directly between albums on separate
        social sites. This service never stores any personal information.</p>
    <% end %>
  </div>

  <div class="facebook provider">
    <div>
      <% if session[:facebook_account_id] %>
        &#x2713; Connected to Facebook!
      <% else %>
        <%= link_to "Connect to Facebook", new_account_path(:provider => "facebook") %>
      <% end %>
    </div>
  </div>

  <div class="flickr provider clearfix">
    <div>
      <% if session[:flickr_account_id] %>
        &#x2713; Connected to Flickr!
      <% else %>
        <%= link_to "Connect to Flickr", new_account_path(:provider => "flickr") %>
      <% end %>
    </div>
  </div>

  <% if session[:flickr_account_id] and session[:facebook_account_id] %>
    <div class="explanation">
      <br/>
      <br/>

      <p><b>Step 1:</b> Click an album to load its photos</p>

      <p><b>Step 2:</b> Drag one of those photos onto a different album</p>
    </div>
  <% end %>
</div>


<div id="accounts_container">
  <!--<div id="connect"></div>-->
  <% @accounts.each do |account| %>
    <div class="<%= account.provider %> account" data-provider="<%= account.provider %>"
    ">
    <h2><%= account.provider %>
      albums <%= link_to "refresh", refresh_path(:provider => account.provider), :class => "refresh" %></h2>
    <% account.albums.each do |album| %>
      <div class="album" data-id="<%= album.id %>">
        <div class="photo">
          <% if album.primary_photo_url %>
            <%= image_tag album.primary_photo_url %>
          <% elsif album.photos and album.photos.length > 0 %>
            <%= image_tag album.photos[0].url %>
          <% else %>
            <%= image_tag "spinner.gif", :class => 'spinner' %>
          <% end %>
          <!-- spinner, or -->
          <!-- primary photo -->
        </div>
        <div class="info" data-name="<%= album.name %>">
          <%= album.name %>
        </div>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>

  <div id="filmstrip">
    <img src="/images/spinner.gif" class="spinner"/>

    <div class="slider"></div>
  </div>

  </body>
</html>